export const GET_PRODUCT = "PRODUCT/GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "PRODUCT/GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "PRODUCT/GET_PRODUCT_ERROR";

export const GET_HOME_PRODUCT = "PRODUCT/GET_HOME_PRODUCT";
export const GET_HOME_PRODUCT_SUCCESS = "PRODUCT/GET_HOME_PRODUCT_SUCCESS";
export const GET_HOME_PRODUCT_ERROR = "PRODUCT/GET_HOME_PRODUCT_ERROR";

export const GET_HOME_PROPOSE = "PRODUCT/GET_HOME_PROPOSE";
export const GET_HOME_PROPOSE_SUCCESS = "PRODUCT/GET_HOME_PROPOSE_SUCCESS";
export const GET_HOME_PROPOSE_ERROR = "PRODUCT/GET_HOME_PROPOSE_ERROR";

export const GET_DETAIL = "PRODUCT/GET_DETAIL";
export const GET_DETAIL_SUCCESS = "PRODUCT/GET_DETAIL_SUCCESS";
export const GET_DETAIL_ERROR = "PRODUCT/GET_DETAIL_ERROR";

export const GET_SUGGEST = "PRODUCT/GET_SUGGEST";
export const GET_SUGGEST_SUCCESS = "PRODUCT/GET_SUGGEST_SUCCESS";
export const GET_SUGGEST_ERROR = "PRODUCT/GET_SUGGEST_ERROR";

export const GET_FEATURE = "PRODUCT/GET_FEATURE";
export const GET_FEATURE_SUCCESS = "PRODUCT/GET_FEATURE_SUCCESS";
export const GET_FEATURE_ERROR = "PRODUCT/GET_FEATURE_ERROR";

export const SEARCH_PRODUCT = "PRODUCT/SEARCH_PRODUCT";
export const SEARCH_PRODUCT_SUCCESS = "PRODUCT/SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_ERROR = "PRODUCT/SEARCH_PRODUCT_ERROR";
